import Head from "next/head";

export default function Home() {
	return (
		<div>
			<Head>
				<title>Exo</title>
				{/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
			</Head>

			<h1>Exo</h1>
		</div>
	);
}
